// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import "@openzeppelin/contracts/token/ERC1155/ERC1155.sol";
import "@openzeppelin/contracts/token/ERC1155/extensions/ERC1155Burnable.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";
import "@openzeppelin/contracts/token/common/ERC2981.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/token/ERC1155/extensions/ERC1155Supply.sol";

/**
 * @title SpiritWolf
 * @notice ERC-1155 Multi-Token Standard
 * @dev Supports multiple token types (fungible + non-fungible)
 *      Generated by NFT Forge — Alsania
 */
contract SpiritWolf is ERC1155, ERC1155Burnable, ERC2981, Ownable, Pausable, ERC1155Supply {

    // Token IDs — define your types here
    uint256 public constant COMMON    = 0;
    uint256 public constant RARE      = 1;
    uint256 public constant EPIC      = 2;
    uint256 public constant LEGENDARY = 3;

    uint256 public constant MINT_PRICE = 0.05 ether;
    string public name;

    mapping(uint256 => uint256) public maxSupplyPerType;

    event Withdrawn(address indexed to, uint256 amount);

    constructor() ERC1155("ipfs://qwertyuj") Ownable(msg.sender) {
        name = "SpiritWolf";
        _setDefaultRoyalty(msg.sender, 300);

        // Set max supply per type
        maxSupplyPerType[COMMON]    = 5000;
        maxSupplyPerType[RARE]      = 2000;
        maxSupplyPerType[EPIC]      = 500;
        maxSupplyPerType[LEGENDARY] = 100;
    }

    // ─── PUBLIC MINT ───
    function mint(address to, uint256 id, uint256 amount) external payable {
        require(id <= LEGENDARY, "Invalid token type");
        require(msg.value >= MINT_PRICE * amount, "Insufficient ETH");
        require(totalSupply(id) + amount <= maxSupplyPerType[id], "Exceeds supply");
        _mint(to, id, amount, "");
    }

    function mintBatch(address to, uint256[] calldata ids, uint256[] calldata amounts) external payable onlyOwner {
        _mintBatch(to, ids, amounts, "");
    }

    // ─── ADMIN ───
    function setURI(string calldata newURI) external onlyOwner { _setURI(newURI); }
    function setRoyalty(address receiver, uint96 fee) external onlyOwner { _setDefaultRoyalty(receiver, fee); }
    function setMaxSupply(uint256 id, uint256 newMax) external onlyOwner { maxSupplyPerType[id] = newMax; }
    function pause() external onlyOwner { _pause(); }
    function unpause() external onlyOwner { _unpause(); }

    function withdraw() external onlyOwner {
        uint256 bal = address(this).balance;
        (bool ok,) = payable(owner()).call{value: bal}("");
        require(ok, "Withdraw failed");
        emit Withdrawn(owner(), bal);
    }

    // ─── OVERRIDES ───

    function _update(address from, address to, uint256[] memory ids, uint256[] memory values)
        internal override(ERC1155, ERC1155Supply) {
        if (paused()) revert EnforcedPause();
        super._update(from, to, ids, values);
    }

    function supportsInterface(bytes4 interfaceId)
        public view override(ERC1155, ERC2981) returns (bool)
    { return super.supportsInterface(interfaceId); }
}
