// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

// ERC-721A by Chiru Labs (azuki) — install: npm install erc721a
import "erc721a/contracts/ERC721A.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/token/common/ERC2981.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";


/**
 * @title WolfPack
 * @notice ERC-721A — Gas-optimized NFT Collection
 * @dev Azuki ERC-721A: ~90% gas savings on batch mints
 *      Generated by NFT Forge — Alsania
 */
contract WolfPack is ERC721A, ERC2981, Ownable, ReentrancyGuard, Pausable {

    uint256 public constant MAX_SUPPLY = 10000;
    uint256 public constant MINT_PRICE = 0.05 ether;
    uint256 public constant MAX_PER_WALLET = 10;
    uint256 public constant MAX_PER_TX = 5;

    bool public publicMintActive;
    string private _baseTokenURI;



    event PublicMintToggled(bool active);
    event Withdrawn(address indexed to, uint256 amount);

    constructor() ERC721A("WolfPack", "WPCK") Ownable(msg.sender) {
        _setDefaultRoyalty(msg.sender, 300);
        _baseTokenURI = "ipfs://Qwefghhjm";
        _mint(msg.sender, 10); // Owner reserve
    }

    // ─── PUBLIC MINT ───
    function mint(uint256 quantity) external payable nonReentrant {
        require(publicMintActive, "Public mint not active");
        require(quantity > 0 && quantity <= MAX_PER_TX, "Invalid quantity");
        require(totalSupply() + quantity <= MAX_SUPPLY, "Exceeds max supply");
        require(_numberMinted(msg.sender) + quantity <= MAX_PER_WALLET, "Exceeds wallet limit");
        require(msg.value >= MINT_PRICE * quantity, "Insufficient ETH");
        _mint(msg.sender, quantity);
    }


    // ─── METADATA ───
    function _baseURI() internal view override returns (string memory) { return _baseTokenURI; }


    // ─── ADMIN ───
    function ownerMint(address to, uint256 quantity) external onlyOwner {
        require(totalSupply() + quantity <= MAX_SUPPLY, "Exceeds max supply");
        _mint(to, quantity);
    }
    function setPublicMint(bool active) external onlyOwner { publicMintActive = active; emit PublicMintToggled(active); }
    function setBaseURI(string calldata uri) external onlyOwner { _baseTokenURI = uri; }


    function pause() external onlyOwner { _pause(); }
    function unpause() external onlyOwner { _unpause(); }

    function withdraw() external onlyOwner {
        uint256 bal = address(this).balance;
        require(bal > 0, "Nothing to withdraw");
        (bool ok,) = payable(owner()).call{value: bal}("");
        require(ok, "Withdraw failed");
        emit Withdrawn(owner(), bal);
    }

    // ─── OVERRIDES ───
    function supportsInterface(bytes4 interfaceId)
        public view override(ERC721A, ERC2981) returns (bool)
    { return super.supportsInterface(interfaceId); }

    function totalMinted() external view returns (uint256) { return totalSupply(); }
    function remaining() external view returns (uint256) { return MAX_SUPPLY - totalSupply(); }
}
